DROP TABLE SPRINGP.MEMBER;
DROP TABLE SPRINGP.RESERVATION;
DROP TABLE SPRINGP.CULTURAL_FACILITY;
DROP TABLE SPRINGP.PHYSICAL_FACILITY;

CREATE TABLE "SPRINGP"."MEMBER"
(
    "USER_NO"       NUMBER,
    "PROVIDER"      VARCHAR2(100),
    "PROVIDER_ID"   VARCHAR2(100),
    "USERNAME"      VARCHAR2(100),
    "EMAIL"         VARCHAR2(100),
    "PROFILE_IMAGE" VARCHAR2(512),
    "ADDRESS"       VARCHAR2(255),
    "INTEREST"      VARCHAR2(100),
    "LATEST_SEARCH" VARCHAR2(100)
);

CREATE TABLE "SPRINGP"."RESERVATION"
(
    "RE_ID"     VARCHAR2(100 BYTE),
    "USER_NO"   NUMBER,
    "RE_DATE"   DATE DEFAULT SYSDATE,
    "CATEGORY"  VARCHAR2(100 BYTE),
    "SVCID"     VARCHAR2(100 BYTE),
    "RE_STATUS" VARCHAR2(50 BYTE)
);

CREATE TABLE "SPRINGP"."CULTURAL_FACILITY"
(
    "SVCID"      VARCHAR2(255 BYTE),
    "MINCLASSNM" VARCHAR2(255 BYTE),
    "SVCSTATNM"  VARCHAR2(255 BYTE),
    "SVCNM"      VARCHAR2(255 BYTE),
    "PLACENM"    VARCHAR2(255 BYTE),
    "X"          VARCHAR2(255 BYTE),
    "Y"          VARCHAR2(255 BYTE),
    "SVCOPNBGNDT"  VARCHAR2(255 BYTE),
    "SVCOPNENDDT"  VARCHAR2(255 BYTE),
    "RCPTBGNDT"  VARCHAR2(255 BYTE),
    "RCPTENDDT"  VARCHAR2(255 BYTE),
    "AREANM"     VARCHAR2(255 BYTE),
    "TELNO"      VARCHAR2(255 BYTE),
    "IMGURL"     VARCHAR2(255 BYTE),
    "REVSTDDAY"  VARCHAR2(255 BYTE)
);

CREATE TABLE "SPRINGP"."PHYSICAL_FACILITY"
(
    "SVCID"      VARCHAR2(255 BYTE),
    "MINCLASSNM" VARCHAR2(255 BYTE),
    "SVCSTATNM"  VARCHAR2(255 BYTE),
    "SVCNM"      VARCHAR2(255 BYTE),
    "PLACENM"    VARCHAR2(255 BYTE),
    "X"          VARCHAR2(255 BYTE),
    "Y"          VARCHAR2(255 BYTE),
    "SVCOPNBGNDT"  VARCHAR2(255 BYTE),
    "SVCOPNENDDT"  VARCHAR2(255 BYTE),
    "RCPTBGNDT"  VARCHAR2(255 BYTE),
    "RCPTENDDT"  VARCHAR2(255 BYTE),
    "AREANM"     VARCHAR2(255 BYTE),
    "TELNO"      VARCHAR2(255 BYTE),
    "IMGURL"     VARCHAR2(255 BYTE),
    "REVSTDDAY"  VARCHAR2(255 BYTE)
);


CREATE TABLE "SPRINGP"."REPLY"
(	"REPLY_NO" NUMBER,
     "REPLY_CONTENT" VARCHAR2(400 BYTE),
     "REF_SVCID" VARCHAR(255 BYTE),
     "REPLY_WRITER" NUMBER,
     "CREATE_DATE" DATE DEFAULT SYSDATE,
     "STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y'
);

CREATE TABLE "SUPPORT" (
    "SUPPORT_NO"	NUMBER
       CONSTRAINT PK_SUPPORT PRIMARY KEY ,
    "SVCID"	NUMBER
       CONSTRAINT SP_SVCID	NOT NULL,
    "USER_NO"	NUMBER
       CONSTRAINT SP_USER NOT NULL,
    "MERCHANT_UID"  VARCHAR2(100)
       CONSTRAINT SP_MU_NN NOT NULL,
    "AMOUNT"	NUMBER
       CONSTRAINT SP_AM_NN NOT NULL,
    "STATUS"    VARCHAR2(20)
       CONSTRAINT SP_ST_NN NOT NULL,
    "PAY_TIME"	DATE DEFAULT SYSDATE,
    "DP_WD" VARCHAR2(2) CHECK(DP_WD IN('DP','WD')),
    "WD_STATUS" VARCHAR2(10)
);



-- create sequence SPRINGP.SEQ_RE_NO;
-- create sequence SPRINGP.SEQ_UNO;
-- CREATE SEQUENCE SPRINGP.SEQ_RNO;
