CREATE TABLE "SPRINGP"."USER"
(	"USER_NO" NUMBER,
     "USER_ID" VARCHAR2(100 BYTE),
     "USER_NAME" VARCHAR2(100 BYTE),
     "ADDRESS" VARCHAR2(255 BYTE),
     "INTEREST" VARCHAR2(100 BYTE),
     "SEARCH" VARCHAR2(100 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

COMMENT ON COLUMN "SPRINGP"."USER"."USER_NO" IS '회원번호';
   COMMENT ON COLUMN "SPRINGP"."USER"."USER_ID" IS '아이디';
   COMMENT ON COLUMN "SPRINGP"."USER"."USER_NAME" IS '회원이름';
   COMMENT ON COLUMN "SPRINGP"."USER"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "SPRINGP"."USER"."INTEREST" IS '관심사';
   COMMENT ON COLUMN "SPRINGP"."USER"."SEARCH" IS '최근검색';
REM INSERTING into SPRINGP."USER"
SET DEFINE OFF;

CREATE UNIQUE INDEX "SPRINGP"."PK_MEMBER" ON "SPRINGP"."USER" ("USER_NO")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;

ALTER TABLE "SPRINGP"."USER" MODIFY ("USER_NO" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."USER" MODIFY ("USER_ID" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."USER" MODIFY ("ADDRESS" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."USER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("USER_NO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;


CREATE TABLE "SPRINGP"."RESERVATION"
(	"RE_ID" VARCHAR2(100 BYTE),
     "USER_NO" NUMBER,
     "RE_DATE" DATE DEFAULT SYSDATE,
     "CATEGORY" VARCHAR2(100 BYTE),
     "SVCID" VARCHAR2(100 BYTE),
     "RE_STATUS" VARCHAR2(50 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

COMMENT ON COLUMN "SPRINGP"."RESERVATION"."RE_ID" IS '예약번호';
   COMMENT ON COLUMN "SPRINGP"."RESERVATION"."USER_NO" IS '회원번호';
   COMMENT ON COLUMN "SPRINGP"."RESERVATION"."RE_DATE" IS '예약일자';
   COMMENT ON COLUMN "SPRINGP"."RESERVATION"."CATEGORY" IS '시설분류';
   COMMENT ON COLUMN "SPRINGP"."RESERVATION"."SVCID" IS '서비스ID';
   COMMENT ON COLUMN "SPRINGP"."RESERVATION"."RE_STATUS" IS '예약상태';
REM INSERTING into SPRINGP.RESERVATION
SET DEFINE OFF;


ALTER TABLE "SPRINGP"."RESERVATION" MODIFY ("RE_ID" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."RESERVATION" MODIFY ("USER_NO" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."RESERVATION" MODIFY ("RE_DATE" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."RESERVATION" MODIFY ("CATEGORY" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."RESERVATION" MODIFY ("RE_STATUS" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."RESERVATION" MODIFY ("SVCID" NOT NULL ENABLE);


CREATE TABLE "SPRINGP"."CULTURAL_FACILITY"
(	"SVCID" VARCHAR2(255 BYTE),
     "MINCLASSNM" VARCHAR2(50 BYTE),
     "SVCSTATNM" VARCHAR2(50 BYTE),
     "SVCNM" VARCHAR2(255 BYTE),
     "PLACENM" VARCHAR2(100 BYTE),
     "X" VARCHAR2(80 BYTE),
     "Y" VARCHAR2(80 BYTE),
     "RCPTBGNDT" VARCHAR2(255 BYTE),
     "RCPTENDDT" VARCHAR2(255 BYTE),
     "AREANM" VARCHAR2(50 BYTE),
     "TELNO" VARCHAR2(50 BYTE),
     "REVSTDDAY" VARCHAR2(255 BYTE),
     "SVCURL" VARCHAR2(255 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."SVCID" IS '서비스ID';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."MINCLASSNM" IS '소분류명';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."SVCSTATNM" IS '서비스상태';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."SVCNM" IS '서비스명';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."PLACENM" IS '장소명';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."X" IS '장소X좌표';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."Y" IS '장소Y좌표';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."RCPTBGNDT" IS '접수시작일시';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."RCPTENDDT" IS '접수종료일시';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."AREANM" IS '지역명';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."TELNO" IS '전화번호';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."REVSTDDAY" IS '취소기간 기준일까지';
   COMMENT ON COLUMN "SPRINGP"."CULTURAL_FACILITY"."SVCURL" IS '이미지경로';
SET DEFINE OFF;


CREATE UNIQUE INDEX "SPRINGP"."PK_CULTURAL_FACILITY" ON "SPRINGP"."CULTURAL_FACILITY" ("SVCID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;


ALTER TABLE "SPRINGP"."CULTURAL_FACILITY" MODIFY ("SVCSTATNM" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."CULTURAL_FACILITY" MODIFY ("SVCID" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."CULTURAL_FACILITY" MODIFY ("MINCLASSNM" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."CULTURAL_FACILITY" MODIFY ("PLACENM" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."CULTURAL_FACILITY" ADD CONSTRAINT "PK_CULTURAL_FACILITY" PRIMARY KEY ("SVCID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
ALTER TABLE "SPRINGP"."CULTURAL_FACILITY" MODIFY ("SVCNM" NOT NULL ENABLE);

CREATE TABLE "SPRINGP"."PHYSICAL_FACILITY"
(	"SVCID" VARCHAR2(255 BYTE),
     "MINCLASSNM" VARCHAR2(50 BYTE),
     "SVCSTATNM" VARCHAR2(50 BYTE),
     "SVCNM" VARCHAR2(255 BYTE),
     "PLACENM" VARCHAR2(100 BYTE),
     "X" VARCHAR2(80 BYTE),
     "Y" VARCHAR2(80 BYTE),
     "RCPTBGNDT" VARCHAR2(255 BYTE),
     "RCPTENDDT" VARCHAR2(255 BYTE),
     "AREANM" VARCHAR2(50 BYTE),
     "TELNO" VARCHAR2(50 BYTE),
     "REVSTDDAY" VARCHAR2(255 BYTE),
     "SVCURL" VARCHAR2(255 BYTE)
) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."SVCID" IS '서비스ID';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."MINCLASSNM" IS '소분류명';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."SVCSTATNM" IS '서비스상태';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."SVCNM" IS '서비스명';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."PLACENM" IS '장소명';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."X" IS '장소X좌표';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."Y" IS '장소Y좌표';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."RCPTBGNDT" IS '접수시작일시';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."RCPTENDDT" IS '접수종료일시';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."AREANM" IS '지역명';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."TELNO" IS '전화번호';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."REVSTDDAY" IS '취소기간 기준일';
   COMMENT ON COLUMN "SPRINGP"."PHYSICAL_FACILITY"."SVCURL" IS '이미지경로';
REM INSERTING into SPRINGP.PHYSICAL_FACILITY
SET DEFINE OFF;

CREATE UNIQUE INDEX "SPRINGP"."PK_PHYSCICAL_FACILITY" ON "SPRINGP"."PHYSICAL_FACILITY" ("SVCID")
    PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS" ;


ALTER TABLE "SPRINGP"."PHYSICAL_FACILITY" MODIFY ("SVCID" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."PHYSICAL_FACILITY" MODIFY ("MINCLASSNM" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."PHYSICAL_FACILITY" MODIFY ("PLACENM" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."PHYSICAL_FACILITY" ADD CONSTRAINT "PK_PHYSCICAL_FACILITY" PRIMARY KEY ("SVCID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  TABLESPACE "USERS"  ENABLE;
ALTER TABLE "SPRINGP"."PHYSICAL_FACILITY" MODIFY ("SVCNM" NOT NULL ENABLE);
ALTER TABLE "SPRINGP"."PHYSICAL_FACILITY" MODIFY ("SVCSTATNM" NOT NULL ENABLE);



